import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import { registerLicense } from '@syncfusion/ej2-base';
registerLicense('Mgo+DSMBaFt+QHJqVEZrXVNbdV5dVGpAd0N3RGlcdlR1fUUmHVdTRHRcQltiT39bdUZhUXhecnM=;Mgo+DSMBPh8sVXJ1S0R+XVFPd11dXmJWd1p/THNYflR1fV9DaUwxOX1dQl9gSXhScERrWnxceHNUQGc=;ORg4AjUWIQA/Gnt2VFhiQlBEfV5AQmBIYVp/TGpJfl96cVxMZVVBJAtUQF1hSn5Vd0NiUXxdcnxSRWBb;MjQ0Mzc0MEAzMjMxMmUzMDJlMzBoSmdPSWJ0NEpqcUtEMTBLVjMrMytOY2V3ejlJTVZhTjZQc3dwR2c4K0JRPQ==;MjQ0Mzc0MUAzMjMxMmUzMDJlMzBuMk9CVGRYa2dtSWNEbHNCcUg2RE5OZTdZL2ZQamNEOWRZdGVPMWZ1RzY4PQ==;NRAiBiAaIQQuGjN/V0d+Xk9FdlRDX3xKf0x/TGpQb19xflBPallYVBYiSV9jS31TcERlWHddc3ZdTmBeVg==;MjQ0Mzc0M0AzMjMxMmUzMDJlMzBTZHNKWDg4WGt3SnNaNlRXNDRuM3E3eVVHK1U0QzdNZEVKTjlLOGI2UjJrPQ==;MjQ0Mzc0NEAzMjMxMmUzMDJlMzBXSzBuMVk4bWx0MXpkazRDcGZyUGNyMFN0MXhJVXByS3gwbk9TMWR4TkRNPQ==;Mgo+DSMBMAY9C3t2VFhiQlBEfV5AQmBIYVp/TGpJfl96cVxMZVVBJAtUQF1hSn5Vd0NiUXxdcnxdQWRb;MjQ0Mzc0NkAzMjMxMmUzMDJlMzBMYVNWdzFwWUJRL1lmQlE4NjQ0K1ZwWWJxR2tMYkIxZkNFd1dHaHZOelc4PQ==;MjQ0Mzc0N0AzMjMxMmUzMDJlMzBZb3NhdjFoamhMNFNYOGFka3RkQmp4aUF3aTBZbCt0S2lSbzNqUWxYOE80PQ==;MjQ0Mzc0OEAzMjMxMmUzMDJlMzBTZHNKWDg4WGt3SnNaNlRXNDRuM3E3eVVHK1U0QzdNZEVKTjlLOGI2UjJrPQ==');

ReactDOM.render(
  <React.StrictMode>
      <App />
  </React.StrictMode>, 
  document.getElementById('root')
);


